# Generated by Django 4.2.4 on 2023-09-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='expense_amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='expense_description',
        ),
    ]
